# Site settings
title: Iain Dunning - Blog
description: Personal website for Iain Dunning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iaindunning.com" # the base hostname & protocol for your site
permalink: /blog/:title.html

# Build settings
#markdown: redcarpet